import Head from "next/head";
import Header from "@/components/header";

const Admin = () => {
  return (
    <div>
      <Head>
        <title>Admin Dash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-3 gap-4 lg:mx-24">
        <Header />
      </div>
    </div>
  );
};

export default Admin;
