import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/header'
import MainNews from '@/components/mainNews'
import Sidewidget from '@/components/sideWidget'


const Home = () => {
  return (
    <div>
      <Head>
        <title>News Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-3 gap-4 lg:mx-24'>
          <Header/>
          <MainNews/>
          <Sidewidget/>
      </div>
    </div>
  )
}

export default Home;